version: "3.8"

services:
  redisapp:
    image: redis:latest
    container_name: redisapp
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: ./.
    depends_on:
      - redisapp
    ports:
      - 8050:8050
    networks:
      - workshop

volumes:
  redis_data:

networks:
  workshop:
    driver: bridge